### ISSUE TITLE
KOTOR: Cannot create character/start initial module.

### ISSUE THREAD

**Issue by aFoxNamedMorris** [xoreos/xoreos#250]
No matter which combination of class and portrait I select, the game crashes upon attempting to create character.

This is the output:
```
Loading texture pack 2
WARNING: Failed to create texture "M01aa_04a_a0002t" (-1)
    Because: No such image resource "M01aa_04a_a0002t"
WARNING: Failed to create texture "DOR_LHR02_a00004" (-1)
    Because: No such image resource "DOR_LHR02_a00004"
WARNING: Failed to create texture "DOR_LHR02_a00004" (-1)
    Because: No such image resource "DOR_LHR02_a00004"
WARNING: Failed to create texture "DOR_LHR02_a00004" (-1)
    Because: No such image resource "DOR_LHR02_a00004"
WARNING: Failed to create texture "DOR_LHR02_a00004" (-1)
    Because: No such image resource "DOR_LHR02_a00004"
Segmentation fault (core dumped)
```

Xubuntu 18.04

More information available upon request.

**Comment by DrMcCoy** [comment]
Hmm, can you do one or all of the following?

- Compile xoreos with the sanitizers (`export CXXFLAGS="-O2 -fno-omit-frame-pointer -fsanitize=address,undefined"` before running configure or cmake)
- Run xoreos in valgrind (warning, very slow)

Or run xoreos in gdb and give me a backtrace (not as useful as the other two methods).

**Comment by DrMcCoy** [comment]
Oh, and please, use the current master branch for that, i.e. b3fe6230739bda72d57fe70738158ce5ba3e4090, so that I know what's what.

**Comment by aFoxNamedMorris** [comment]
I am using master branch. Will recompile and post the results shortly.

**Comment by aFoxNamedMorris** [comment]
Here is the GDB output:
```
Thread 8 "GameInstance" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffd25a6700 (LWP 24556)]
0x0000555555bf95cc in ?? ()

[Thread 0x7fffd2da7700 (LWP 24555) exited]
[Thread 0x7fffd25a6700 (LWP 24556) exited]
[Thread 0x7fffd35a8700 (LWP 24554) exited]
[Thread 0x7fffd3fff700 (LWP 24553) exited]
[Thread 0x7fffe89e1700 (LWP 24552) exited]
[Thread 0x7fffebc77700 (LWP 24536) exited]

Program terminated with signal SIGSEGV, Segmentation fault.
The program no longer exists.

```

**Comment by DrMcCoy** [comment]
You need to type 'bt' at that gdb prompt and the sanitizer output is missing the output from the sanitizers.

**Comment by aFoxNamedMorris** [comment]
Thanks! Sorry about that. I'll be back with that and the Valgrind data.

**Comment by aFoxNamedMorris** [comment]
Here is the Valgrind data:
```
==29787== Thread 7 GameInstance:                                                                                                                              
==29787== Invalid write of size 8                                                                                                                             
==29787==    at 0x7AD5CC: Engines::KotOR::KotORWidget::setSubScene(Graphics::Aurora::SubSceneQuad*) (in /home/aaronmorris/SRC/xoreos/bin/xoreos)              
==29787==    by 0x7E411B: Engines::KotOR::HUD::setMinimap(Common::UString const&, int, float, float, float, float, float, float, float, float) (in /home/aaron
morris/SRC/xoreos/bin/xoreos)                                                                                                                                 
==29787==    by 0x7E28E7: Engines::KotOR::IngameGUI::setMinimap(Common::UString const&, int, float, float, float, float, float, float, float, float) (in /home
/aaronmorris/SRC/xoreos/bin/xoreos)
==29787==    by 0x7C3DD1: Engines::KotOR::Module::loadModule(Common::UString const&, Common::UString const&, Engines::KotOR::ObjectType) (in /home/aaronmorris
/SRC/xoreos/bin/xoreos)
==29787==    by 0x7C39FA: Engines::KotOR::Module::load(Common::UString const&, Common::UString const&, Engines::KotOR::ObjectType) (in /home/aaronmorris/SRC/x
oreos/bin/xoreos)
==29787==    by 0x7DE17F: Engines::KotOR::CharacterGenerationMenu::start() (in /home/aaronmorris/SRC/xoreos/bin/xoreos)
==29787==    by 0x7DF23D: Engines::KotOR::QuickCharPanel::callbackActive(Engines::Widget&) (in /home/aaronmorris/SRC/xoreos/bin/xoreos)
==29787==    by 0x8DFC54: Engines::GUI::checkWidgetActive(Engines::Widget*) (in /home/aaronmorris/SRC/xoreos/bin/xoreos)
==29787==    by 0x8DFE53: Engines::GUI::mouseUp(SDL_Event const&) (in /home/aaronmorris/SRC/xoreos/bin/xoreos)
==29787==    by 0x8DECCE: Engines::GUI::processEventQueue() (in /home/aaronmorris/SRC/xoreos/bin/xoreos)
==29787==    by 0x8DE897: Engines::GUI::run(unsigned int) (in /home/aaronmorris/SRC/xoreos/bin/xoreos)
==29787==    by 0x8DF743: Engines::GUI::sub(Engines::GUI&, unsigned int, bool, bool) (in /home/aaronmorris/SRC/xoreos/bin/xoreos)
==29787==  Address 0x100 is not stack'd, malloc'd or (recently) free'd                                                                                        
==29787==                                                                                                                                                     
==29787==
==29787== Process terminating with default action of signal 11 (SIGSEGV)                                                                                      
==29787==  Access not within mapped region at address 0x100                                                                                                   
==29787==    at 0x7AD5CC: Engines::KotOR::KotORWidget::setSubScene(Graphics::Aurora::SubSceneQuad*) (in /home/aaronmorris/SRC/xoreos/bin/xoreos)              
==29787==    by 0x7E411B: Engines::KotOR::HUD::setMinimap(Common::UString const&, int, float, float, float, float, float, float, float, float) (in /home/aaron
morris/SRC/xoreos/bin/xoreos)
==29787==    by 0x7E28E7: Engines::KotOR::IngameGUI::setMinimap(Common::UString const&, int, float, float, float, float, float, float, float, float) (in /home
/aaronmorris/SRC/xoreos/bin/xoreos)
==29787==    by 0x7C3DD1: Engines::KotOR::Module::loadModule(Common::UString const&, Common::UString const&, Engines::KotOR::ObjectType) (in /home/aaronmorris
/SRC/xoreos/bin/xoreos)
==29787==    by 0x7C39FA: Engines::KotOR::Module::load(Common::UString const&, Common::UString const&, Engines::KotOR::ObjectType) (in /home/aaronmorris/SRC/x
oreos/bin/xoreos)
==29787==    by 0x7DE17F: Engines::KotOR::CharacterGenerationMenu::start() (in /home/aaronmorris/SRC/xoreos/bin/xoreos)
==29787==    by 0x7DF23D: Engines::KotOR::QuickCharPanel::callbackActive(Engines::Widget&) (in /home/aaronmorris/SRC/xoreos/bin/xoreos)
==29787==    by 0x8DFC54: Engines::GUI::checkWidgetActive(Engines::Widget*) (in /home/aaronmorris/SRC/xoreos/bin/xoreos)
==29787==    by 0x8DFE53: Engines::GUI::mouseUp(SDL_Event const&) (in /home/aaronmorris/SRC/xoreos/bin/xoreos)
==29787==    by 0x8DECCE: Engines::GUI::processEventQueue() (in /home/aaronmorris/SRC/xoreos/bin/xoreos)
==29787==    by 0x8DE897: Engines::GUI::run(unsigned int) (in /home/aaronmorris/SRC/xoreos/bin/xoreos)
==29787==    by 0x8DF743: Engines::GUI::sub(Engines::GUI&, unsigned int, bool, bool) (in /home/aaronmorris/SRC/xoreos/bin/xoreos)
==29787==  If you believe this happened as a result of a stack                                                                                        [5/1981]
==29787==  overflow in your program's main thread (unlikely but
==29787==  possible), you can try to increase the size of the
==29787==  main thread stack using the --main-stacksize= flag.
==29787==  The main thread stack size used in this run was 8388608.
==29787==
==29787== HEAP SUMMARY:
==29787==     in use at exit: 146,690,055 bytes in 552,851 blocks
==29787==   total heap usage: 5,162,790 allocs, 4,609,939 frees, 1,935,877,662 bytes allocated
==29787==
==29787== LEAK SUMMARY:
==29787==    definitely lost: 16 bytes in 1 blocks
==29787==    indirectly lost: 176 bytes in 4 blocks
==29787==      possibly lost: 18,426,546 bytes in 2,214 blocks
==29787==    still reachable: 128,263,317 bytes in 550,632 blocks
==29787==                       of which reachable via heuristic:
==29787==                         newarray           : 14,456 bytes in 30 blocks
==29787==                         multipleinheritance: 176 bytes in 2 blocks
==29787==         suppressed: 0 bytes in 0 blocks
==29787== Rerun with --leak-check=full to see details of leaked memory
==29787==
==29787== For counts of detected and suppressed errors, rerun with: -v
==29787== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 8 from 1)
Segmentation fault (core dumped)
```

And here is the GDB output from the `bt` command:
```
#0  0x0000555555bf95cc in ?? ()
#1  0x00007fffb4ca3b60 in ?? ()
#2  0x0000000000000000 in ?? ()
```

**Comment by aFoxNamedMorris** [comment]
Thank you so much! I'm on it.
