### ISSUE TITLE
JADE: Segfault when entering the first area

### ISSUE THREAD

**Issue by DrMcCoy** [xoreos/xoreos#349]
```
/home/drmccoy/projects/xoreos/xoreos/src/engines/jade/script/functions_object.cpp:327:53: runtime error: member call on null pointer of type 'struct Object'
AddressSanitizer:DEADLYSIGNAL
=================================================================
==27121==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x559c8f0deaf2 bp 0x7f093bdf12a0 sp 0x7f093bdf1280 T7)
==27121==The signal is caused by a READ memory access.
==27121==Hint: address points to the zero page.
    #0 0x559c8f0deaf1 in Engines::Jade::Functions::getPriorActivation(Aurora::NWScript::FunctionContext&) /home/drmccoy/projects/xoreos/xoreos/src/engines/jade/script/functions_object.cpp:327
    #1 0x559c8f0cd452 in boost::_mfi::mf1<void, Engines::Jade::Functions, Aurora::NWScript::FunctionContext&>::operator()(Engines::Jade::Functions*, Aurora::NWScript::FunctionContext&) const /usr/include/boost/bind/mem_fn_template.hpp:165
    #2 0x559c8f0cd452 in void boost::_bi::list2<boost::_bi::value<Engines::Jade::Functions*>, boost::arg<1> >::operator()<boost::_mfi::mf1<void, Engines::Jade::Functions, Aurora::NWScript::FunctionContext&>, boost::_bi::rrlist1<Aurora::NWScript::FunctionContext&> >(boost::_bi::type<void>, boost::_mfi::mf1<void, Engines::Jade::Functions, Aurora::NWScript::FunctionContext&>&, boost::_bi::rrlist1<Aurora::NWScript::FunctionContext&>&, int) /usr/include/boost/bind/bind.hpp:319
    #3 0x559c8f0cd452 in void boost::_bi::bind_t<void, boost::_mfi::mf1<void, Engines::Jade::Functions, Aurora::NWScript::FunctionContext&>, boost::_bi::list2<boost::_bi::value<Engines::Jade::Functions*>, boost::arg<1> > >::operator()<Aurora::NWScript::FunctionContext&>(Aurora::NWScript::FunctionContext&) /usr/include/boost/bind/bind.hpp:1306
    #4 0x559c8f0cd452 in boost::detail::function::void_function_obj_invoker1<boost::_bi::bind_t<void, boost::_mfi::mf1<void, Engines::Jade::Functions, Aurora::NWScript::FunctionContext&>, boost::_bi::list2<boost::_bi::value<Engines::Jade::Functions*>, boost::arg<1> > >, void, Aurora::NWScript::FunctionContext&>::invoke(boost::detail::function::function_buffer&, Aurora::NWScript::FunctionContext&) /usr/include/boost/function/function_template.hpp:159
    #5 0x559c90a53d59 in boost::function1<void, Aurora::NWScript::FunctionContext&>::operator()(Aurora::NWScript::FunctionContext&) const /usr/include/boost/function/function_template.hpp:759
    #6 0x559c90a53d59 in Aurora::NWScript::FunctionManager::call(unsigned int, Aurora::NWScript::FunctionContext&) const /home/drmccoy/projects/xoreos/xoreos/src/aurora/nwscript/functionman.cpp:109
    #7 0x559c90a97020 in Aurora::NWScript::NCSFile::callEngine(Aurora::NWScript::FunctionContext&, unsigned int, unsigned char) /home/drmccoy/projects/xoreos/xoreos/src/aurora/nwscript/ncsfile.cpp:588
    #8 0x559c90a98549 in Aurora::NWScript::NCSFile::o_action(Aurora::NWScript::NCSFile::InstructionType) /home/drmccoy/projects/xoreos/xoreos/src/aurora/nwscript/ncsfile.cpp:635
    #9 0x559c90a723dc in Aurora::NWScript::NCSFile::executeStep() /home/drmccoy/projects/xoreos/xoreos/src/aurora/nwscript/ncsfile.cpp:419
    #10 0x559c90a740e9 in Aurora::NWScript::NCSFile::execute(Aurora::NWScript::ObjectReference, Aurora::NWScript::ObjectReference) /home/drmccoy/projects/xoreos/xoreos/src/aurora/nwscript/ncsfile.cpp:388
    #11 0x559c90a7c224 in Aurora::NWScript::NCSFile::run(Aurora::NWScript::ScriptState const&, Aurora::NWScript::ObjectReference, Aurora::NWScript::ObjectReference) /home/drmccoy/projects/xoreos/xoreos/src/aurora/nwscript/ncsfile.cpp:381
    #12 0x559c8f0c8ff3 in Engines::Jade::ScriptContainer::runScript(Common::UString const&, Aurora::NWScript::ScriptState const&, Aurora::NWScript::ObjectReference, Aurora::NWScript::ObjectReference) /home/drmccoy/projects/xoreos/xoreos/src/engines/jade/script/container.cpp:133
    #13 0x559c8f0c926d in Engines::Jade::ScriptContainer::runScript(Common::UString const&, Aurora::NWScript::ObjectReference, Aurora::NWScript::ObjectReference) /home/drmccoy/projects/xoreos/xoreos/src/engines/jade/script/container.cpp:120
    #14 0x559c8f08b9db in Engines::Jade::Area::show() /home/drmccoy/projects/xoreos/xoreos/src/engines/jade/area.cpp:106
    #15 0x559c8f067d4b in Engines::Jade::Module::enterArea() /home/drmccoy/projects/xoreos/xoreos/src/engines/jade/module.cpp:223
    #16 0x559c8f068947 in Engines::Jade::Module::enter() /home/drmccoy/projects/xoreos/xoreos/src/engines/jade/module.cpp:209
    #17 0x559c8f060ee5 in Engines::Jade::Game::runModule() /home/drmccoy/projects/xoreos/xoreos/src/engines/jade/game.cpp:95
    #18 0x559c8f065c6a in Engines::Jade::Game::run() /home/drmccoy/projects/xoreos/xoreos/src/engines/jade/game.cpp:78
    #19 0x559c8f05409a in Engines::Jade::JadeEngine::run() /home/drmccoy/projects/xoreos/xoreos/src/engines/jade/jade.cpp:169
    #20 0x559c8fb06a66 in Engines::GameInstanceEngine::run() /home/drmccoy/projects/xoreos/xoreos/src/engines/enginemanager.cpp:222
    #21 0x559c8fb08660 in Engines::EngineManager::run(Engines::GameInstance&) const /home/drmccoy/projects/xoreos/xoreos/src/engines/enginemanager.cpp:249
    #22 0x559c8fb0a02b in Engines::GameThread::threadMethod() /home/drmccoy/projects/xoreos/xoreos/src/engines/gamethread.cpp:87
    #23 0x559c90b802c3 in Common::Thread::threadHelper(void*) /home/drmccoy/projects/xoreos/xoreos/src/common/thread.cpp:113
    #24 0x7f09496997bb in SDL_RunThread /var/tmp/portage/media-libs/libsdl2-2.0.8-r2/work/SDL2-2.0.8/src/thread/SDL_thread.c:283
    #25 0x7f0949700228 in RunThread /var/tmp/portage/media-libs/libsdl2-2.0.8-r2/work/SDL2-2.0.8/src/thread/pthread/SDL_systhread.c:74
    #26 0x7f094a2f59a9 in start_thread /var/tmp/portage/sys-libs/glibc-2.27-r6/work/glibc-2.27/nptl/pthread_create.c:463
    #27 0x7f0945cbc56e in clone (/lib64/libc.so.6+0x10456e)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV /home/drmccoy/projects/xoreos/xoreos/src/engines/jade/script/functions_object.cpp:327 in Engines::Jade::Functions::getPriorActivation(Aurora::NWScript::FunctionContext&)
Thread T7 (GameInstance) created by T0 here:
    #0 0x7f094a558b73 in __interceptor_pthread_create /var/tmp/portage/sys-devel/gcc-8.2.0-r2/work/gcc-8.2.0/libsanitizer/asan/asan_interceptors.cc:202
    #1 0x7f0949700296 in SDL_SYS_CreateThread /var/tmp/portage/media-libs/libsdl2-2.0.8-r2/work/SDL2-2.0.8/src/thread/pthread/SDL_systhread.c:115

==27121==ABORTING
```

@seedhartha *poke* :P

**Comment by seedhartha** [comment]
#352 fixes it.

**Comment by DrMcCoy** [comment]
Thanks! :)
